/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QKART_SANITY_LOGIN.Module1;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import java.sql.Timestamp;
import java.util.ArrayList;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.BrowserType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import java.io.IOException;
import org.openqa.selenium.WindowType;
import java.util.concurrent.TimeUnit;




public class QkartSanity {

    public static String lastGeneratedUserName;


    public static RemoteWebDriver createDriver() throws MalformedURLException {
        // Launch Browser using Zalenium
        final DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setBrowserName(BrowserType.CHROME);
        RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:8082/wd/hub"), capabilities);

        return driver;
    }

    public static void logStatus(String type, String message, String status) {

        System.out.println(String.format("%s |  %s  |  %s | %s", String.valueOf(java.time.LocalDateTime.now()), type,
                message, status));
    }

    public static void takeScreenshot(WebDriver driver, String screenshotType, String description) {
        // TODO: CRIO_TASK_MODULE_SYNCHRONISATION - Implement method using below steps
        /*
         * 1. Check if the folder "/screenshots" exists, create if it doesn't
         * 2. Generate a unique string using the timestamp
         * 3. Capture screenshot
         * 4. Save the screenshot inside the "/screenshots" folder using the following
         * naming convention: screenshot_<Timestamp>_<ScreenshotType>_<Description>.png
         * eg: screenshot_2022-03-05T06:59:46.015489_StartTestcase_Testcase01.png
         */
  
        String folderPath = System.getProperty("user.dir") + File.separator + "screenshots"; // change as needed

        File folder = new File(folderPath);

        if (!folder.exists()) {
            boolean created = folder.mkdirs(); // mkdirs() creates parent dirs too
            if (created) {
                System.out.println("Folder created: " + folderPath);
            } else {
                System.out.println("Failed to create folder!");
            }
        } else {
            System.out.println("Folder already exists: " + folderPath);
        }
        TakesScreenshot ts = (TakesScreenshot) driver;
        File sourceFile = ts.getScreenshotAs(OutputType.FILE);
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        File destinationFile = new File(folderPath+File.separator+"screenshot_"+timestamp+"_"+screenshotType+"_"+description+".png");
        try {
            FileUtils.copyFile(sourceFile, destinationFile);
        } catch (IOException e) {
            e.printStackTrace();
        }

        
    }

    /*
     * Testcase01: Verify the functionality of Login button on the Home page
     */
    public static Boolean TestCase01(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver,"startTestCase","TestCase01");
        Boolean status;
        logStatus("Start TestCase", "Test Case 1: Verify User Registration", "DONE");

        // Visit the Registration page and register a new user
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("TestCase 1", "Test Case Pass. User Registration Pass", "FAIL");
            logStatus("End TestCase", "Test Case 1: Verify user Registration : ", status ? "PASS" : "FAIL");

            // Return False as the test case Fails
            return false;
        } else {
            logStatus("TestCase 1", "Test Case Pass. User Registration Pass", "PASS");
        }

        // Save the last generated username
        lastGeneratedUserName = registration.lastGeneratedUsername;
        // Visit the login page and login with the previuosly registered user
        Login login = new Login(driver);
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        logStatus("Test Step", "User Perform Login: ", status ? "PASS" : "FAIL");
        if (!status) {
            logStatus("End TestCase", "Test Case 1: Verify user Registration : ", status ? "PASS" : "FAIL");
            return false;
        }

        // Visit the home page and log out the logged in user
        Home home = new Home(driver);
        status = home.PerformLogout();
        logStatus("End TestCase", "Test Case 1: Verify user Registration : ", status ? "PASS" : "FAIL");
        takeScreenshot(driver,"endTestCase","TestCase01");
        return status;
    }

    /*
     * Verify that an existing user is not allowed to re-register on QKart
     */
    public static Boolean TestCase02(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver,"startTestCase","TestCase02");
        Boolean status;
        logStatus("Start Testcase", "Test Case 2: Verify User Registration with an existing username ", "DONE");

        // Visit the Registration page and register a new user
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        logStatus("Test Step", "User Registration : ", status ? "PASS" : "FAIL");
        if (!status) {
            logStatus("End TestCase", "Test Case 2: Verify user Registration : ", status ? "PASS" : "FAIL");
            return false;

        }

        // Save the last generated username
        lastGeneratedUserName = registration.lastGeneratedUsername;
        System.out.println(lastGeneratedUserName);

        // Visit the Registration page and try to register using the previously
        // registered user's credentials
        registration.navigateToRegisterPage();
        status = registration.registerUser(lastGeneratedUserName, "abc@123", false);

        // If status is true, then registration succeeded, else registration has
        // failed. In this case registration failure means Success
        logStatus("End TestCase", "Test Case 2: Verify user Registration : ", status ? "FAIL" : "PASS");
        takeScreenshot(driver,"endTestCase","TestCase02");
        return !status;
    }

    /*
     * Verify the functinality of the search text box
     */
    public static Boolean TestCase03(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver,"startTestCase","TestCase03");
        logStatus("TestCase 3", "Start test case : Verify functionality of search box ", "DONE");
        boolean status;

        // Visit the home page
        Home homePage = new Home(driver);
        homePage.navigateToHome();

        // SLEEP_STMT_01 : Wait for Page to Load
        // Thread.sleep(5000);

        // Search for the "yonex" product
        status = homePage.searchForProduct("yonex");
        if (!status) {
            logStatus("TestCase 3", "Test Case Failure. Unable to search for given product", "FAIL");
            return false;
        }

        // Fetch the search results
        List<WebElement> searchResults = homePage.getSearchResults();

        // Verify the search results are available
        if (searchResults.size() == 0) {
            logStatus("TestCase 3", "Test Case Failure. There were no results for the given search string", "FAIL");
            return false;
        }

        for (WebElement webElement : searchResults) {
            // Create a SearchResult object from the parent element
            SearchResult resultelement = new SearchResult(webElement);
            // Verify that all results contain the searched text
            String elementText = resultelement.getTitleofResult();
            
            if (!elementText.toUpperCase().trim().contains("YONEX")) {
                logStatus("TestCase 3", "Test Case Failure. Test Results contains un-expected values: " + elementText,
                        "FAIL");
                return false;
            }
        }

        logStatus("Step Success", "Successfully validated the search results ", "PASS");
        // SLEEP_STMT_02
        // Thread.sleep(2000);

        // Search for product
        status = homePage.searchForProduct("Gesundheit");
        if (!status) {
            logStatus("TestCase 3", "Test Case Failure. Unable to search for given product", "FAIL");
            return false;
        }

        // Verify no search results are found
        searchResults = homePage.getSearchResults();
        if (searchResults.size() == 0) {
            if (homePage.isNoResultFound()) {
                logStatus("Step Success", "Successfully validated that no products found message is displayed", "PASS");
            }
            logStatus("TestCase 3", "Test Case PASS. Verified that no search results were found for the given text",
                    "PASS");
        } else {
            logStatus("TestCase 3", "Test Case Fail. Expected: no results , actual: Results were available", "FAIL");
            return false;
        }
        takeScreenshot(driver,"endTestCase","TestCase03");
        return true;
    }

    /*
     * Verify the presence of size chart and check if the size chart content is as
     * expected
     */
    public static Boolean TestCase04(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver,"startTestCase","TestCase04");
        logStatus("TestCase 4", "Start test case : Verify the presence of size Chart", "DONE");
        boolean status = false;

        // Visit home page
        Home homePage = new Home(driver);
        homePage.navigateToHome();

        // SLEEP_STMT_03 : Wait for page to load
        // Thread.sleep(5000);

        // Search for product and get card content element of search results
        status = homePage.searchForProduct("Running Shoes");
        List<WebElement> searchResults = homePage.getSearchResults();

        // Create expected values
        List<String> expectedTableHeaders = Arrays.asList("Size", "UK/INDIA", "EU", "HEEL TO TOE");
        List<List<String>> expectedTableBody = Arrays.asList(Arrays.asList("6", "6", "40", "9.8"),
                Arrays.asList("7", "7", "41", "10.2"), Arrays.asList("8", "8", "42", "10.6"),
                Arrays.asList("9", "9", "43", "11"), Arrays.asList("10", "10", "44", "11.5"),
                Arrays.asList("11", "11", "45", "12.2"), Arrays.asList("12", "12", "46", "12.6"));

        // Verify size chart presence and content matching for each search result
        for (WebElement webElement : searchResults) {
            SearchResult result = new SearchResult(webElement);

            // Verify if the size chart exists for the search result
            if (result.verifySizeChartExists()) {
                logStatus("Step Success", "Successfully validated presence of Size Chart Link", "PASS");

                // Verify if size dropdown exists
                status = result.verifyExistenceofSizeDropdown(driver);
                logStatus("Step Success", "Validated presence of drop down", status ? "PASS" : "FAIL");

                // Open the size chart
                if (result.openSizechart()) {
                    // Verify if the size chart contents matches the expected values
                    if (result.validateSizeChartContents(expectedTableHeaders, expectedTableBody, driver)) {
                        logStatus("Step Success", "Successfully validated contents of Size Chart Link", "PASS");
                    } else {
                        logStatus("Step Failure", "Failure while validating contents of Size Chart Link", "FAIL");
                    }

                    // Close the size chart modal
                    status = result.closeSizeChart(driver);
                    Thread.sleep(2000);

                } else {
                    logStatus("TestCase 4", "Test Case Fail. Failure to open Size Chart", "FAIL");
                    return false;
                }

            } else {
                logStatus("TestCase 4", "Test Case Fail. Size Chart Link does not exist", "FAIL");
                return false;
            }
        }
        logStatus("TestCase 4", "Test Case PASS. Validated Size Chart Details", "PASS");
        takeScreenshot(driver,"endTestCase","TestCase04");
        return status;
    }

    /*
     * Verify the complete flow of checking out and placing order for products is
     * working correctly
     */
    public static Boolean TestCase05(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver,"startTestCase","TestCase05");
        Boolean status;
        logStatus("Start TestCase", "Test Case 5: Verify Happy Flow of buying products", "DONE");

        // Go to the Register page
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();

        // Register a new user
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("TestCase 5", "Test Case Failure. Happy Flow Test Failed", "FAIL");
        }

        // Save the username of the newly registered user
        lastGeneratedUserName = registration.lastGeneratedUsername;

        // Go to the login page
        Login login = new Login(driver);
        login.navigateToLoginPage();

        // Login with the newly registered user's credentials
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase", "Test Case 5: Happy Flow Test Failed : ", status ? "PASS" : "FAIL");
        }

        // Go to the home page
        Home homePage = new Home(driver);
        homePage.navigateToHome();

        // Find required products by searching and add them to the user's cart
        status = homePage.searchForProduct("Yonex");
        homePage.addProductToCart("YONEX Smash Badminton Racquet");
        status = homePage.searchForProduct("Tan");
        homePage.addProductToCart("Tan Leatherette Weekender Duffle");

        // Click on the checkout button
        homePage.clickCheckout();

        // Add a new address on the Checkout page and select it
        Checkout checkoutPage = new Checkout(driver);
        checkoutPage.addNewAddress("Addr line 1 addr Line 2 addr line 3");
        checkoutPage.selectAddress("Addr line 1 addr Line 2 addr line 3");

        // Place the order
        checkoutPage.placeOrder();
        // SLEEP_STMT_04: Wait for place order to succeed and navigate to Thanks page
        WebDriverWait wait = new WebDriverWait(driver,20);
        try{
            wait.until(ExpectedConditions.urlContains("/thanks"));
        }
        catch(Exception e){
            System.out.println("Here is the error");
        }
        // Thread.sleep(3000);

        // Check if placing order redirected to the Thansk page
        status = driver.getCurrentUrl().endsWith("/thanks");

        // Go to the home page
        homePage.navigateToHome();
        // Thread.sleep(3000);

        // Log out the user
        homePage.PerformLogout();

        logStatus("End TestCase", "Test Case 5: Happy Flow Test Completed : ", status ? "PASS" : "FAIL");
        takeScreenshot(driver,"endTestCase","TestCase05");
        return status;
    }

    /*
     * Verify the quantity of items in cart can be updated
     */
    public static Boolean TestCase06(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver,"startTestCase","TestCase06");
        Boolean status;
        logStatus("Start TestCase", "Test Case 6: Verify that cart can be edited", "DONE");
        
        Register registration = new Register(driver);

        registration.navigateToRegisterPage();

        // Register a new user
        status = registration.registerUser("testUser", "abc@123", true);
        lastGeneratedUserName = registration.lastGeneratedUsername;

        // Go to the login page
        Login login = new Login(driver);
        login.navigateToLoginPage();

        // Login with the newly registered user's credentials
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");

        Home homePage = new Home(driver);
        homePage.navigateToHome();

        // Thread.sleep(5000);

        // Search for the "yonex" product
        status = homePage.searchForProduct("Xtend Smart Watch");
        homePage.addProductToCart("Xtend Smart Watch");
        status = homePage.searchForProduct("Yarine Floor Lamp");
        homePage.addProductToCart("Yarine Floor Lamp");



        // TODO: CRIO_TASK_MODULE_TEST_AUTOMATION - TEST CASE 06: MILESTONE 5

        // TODO: Register a new user

        // TODO: Login using the newly registed user

        // TODO: Add "Xtend Smart Watch" to cart

        // TODO: Add "Yarine Floor Lamp" to cart
        

        // update watch quantity to 2
        homePage.changeProductQuantityinCart("Xtend Smart Watch", 2);

        // update table lamp quantity to 0
        homePage.changeProductQuantityinCart("Yarine Floor Lamp", 0);

        // update watch quantity again to 1
        homePage.changeProductQuantityinCart("Xtend Smart Watch", 1);

        homePage.clickCheckout();

        Checkout checkoutPage = new Checkout(driver);
        checkoutPage.addNewAddress("Addr line 1 addr Line 2 addr line 3");
        checkoutPage.selectAddress("Addr line 1 addr Line 2 addr line 3");

        checkoutPage.placeOrder();
        // Thread.sleep(3000);
        WebDriverWait wait = new WebDriverWait(driver, 10);
        wait.until(d->{
            return d.getCurrentUrl().endsWith("/thanks");
        });

        status = driver.getCurrentUrl().endsWith("/thanks");

        homePage.navigateToHome();
        Thread.sleep(3000);
        homePage.PerformLogout();

        logStatus("End TestCase", "Test Case 6: Verify that cart can be edited: ", status ? "PASS" : "FAIL");
        takeScreenshot(driver,"endTestCase","TestCase06");
        return status;
    }


    public static Boolean TestCase07(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver,"startTestCase","TestCase07");
        Boolean status;
        logStatus("Start TestCase",
                "Test Case 7: Verify that insufficient balance error is thrown when the wallet balance is not enough",
                "DONE");

        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("Step Failure", "User Perform Registration Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 7: Verify that insufficient balance error is thrown when the wallet balance is not enough: ",
                    status ? "PASS" : "FAIL");
            return false;
        }
        lastGeneratedUserName = registration.lastGeneratedUsername;

        Login login = new Login(driver);
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 7: Verify that insufficient balance error is thrown when the wallet balance is not enough: ",
                    status ? "PASS" : "FAIL");
            return false;
        }

        Home homePage = new Home(driver);
        homePage.navigateToHome();
        status = homePage.searchForProduct("Stylecon");
        homePage.addProductToCart("Stylecon 9 Seater RHS Sofa Set");
        Thread.sleep(3000);

        homePage.changeProductQuantityinCart("Stylecon 9 Seater RHS Sofa Set", 10);

        homePage.clickCheckout();

        Checkout checkoutPage = new Checkout(driver);
        checkoutPage.addNewAddress("Addr line 1 addr Line 2 addr line 3");
        checkoutPage.selectAddress("Addr line 1 addr Line 2 addr line 3");

        checkoutPage.placeOrder();
        Thread.sleep(3000);

        status = checkoutPage.verifyInsufficientBalanceMessage();

        logStatus("End TestCase",
                "Test Case 7: Verify that insufficient balance error is thrown when the wallet balance is not enough: ",
                status ? "PASS" : "FAIL");
        takeScreenshot(driver,"endTestCase","TestCase07");

        return status;
    }

    public static Boolean TestCase08(RemoteWebDriver driver) throws InterruptedException {
        Boolean status = false;
        takeScreenshot(driver,"startTestCase","TestCase08");
        logStatus("Start TestCase", "Test Case 8: Verify that products added to cart in one tab get reflected in a new tab", "DONE");
        
        Register registration = new Register(driver);

        registration.navigateToRegisterPage();

        // Register a new user
        status = registration.registerUser("testUser", "abc@123", true);
        lastGeneratedUserName = registration.lastGeneratedUsername;

        // Go to the login page
        Login login = new Login(driver);
        login.navigateToLoginPage();

        // Login with the newly registered user's credentials
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");

        Home homePage = new Home(driver);
        homePage.navigateToHome();

        // Thread.sleep(5000);

        // Search for the "yonex" product
        status = homePage.searchForProduct("YONEX Smash Badminton Racquet");
        homePage.addProductToCart("YONEX Smash Badminton Racquet");

        // open a new tab and switch to it
        String originalHandle = driver.getWindowHandle();
        RemoteWebDriver newTab =(RemoteWebDriver) driver.switchTo().newWindow(WindowType.TAB); // new tab
        Home homePage_newTab = new Home(newTab);

        homePage_newTab.navigateToHome(); // navigate in the new tab
        status=homePage_newTab.verifyCartContents(new ArrayList<String>(Arrays.asList("YONEX Smash Badminton Racquet")));
        logStatus("End TestCase",
                "Test Case 8: Verify that products added to cart in one tab get reflected in a new tab: ",
                status ? "PASS" : "FAIL");

        // close it and switch back
        newTab.close(); // closes current (new) tab
        driver.switchTo().window(originalHandle);
        // TODO: CRIO_TASK_MODULE_SYNCHRONISATION -
        takeScreenshot(driver,"endTestCase","TestCase08");
        return status;
    }

    public static Boolean TestCase09(RemoteWebDriver driver) throws InterruptedException {
        // TODO: CRIO_TASK_MODULE_SYNCHRONISATION -
        Boolean status = false;
        takeScreenshot(driver,"startTestCase","TestCase09");
        logStatus("Start TestCase", "Test Case 9: Verify privacy policy and terms of service", "DONE");

        Home homePage = new Home(driver);
        homePage.navigateToHome();

        WebElement privacy_policy_link= driver.findElement(By.linkText("Privacy policy"));

        String old_url=driver.getCurrentUrl();
        privacy_policy_link.click();
        new WebDriverWait(driver, 10).until(driver_ -> driver_.getWindowHandles().size() > 1);

        String new_url=driver.getCurrentUrl();

        status=old_url.equals(new_url);

        if (!status) {
            logStatus("Step Failure", "URL did not change", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 9: Verify privacy policy and terms of service: ",
                    status ? "PASS" : "FAIL");
            return false;
        }

        String originalHandle = driver.getWindowHandle();

        for (String windowHandle : driver.getWindowHandles()) {
            if (!originalHandle.equals(windowHandle)) {
                driver.switchTo().window(windowHandle);
                break;
            }
        }

        try{
            driver.findElement(By.xpath("//*[contains(text(),'Privacy Policy')]"));
        }
        catch(Exception e){
            logStatus("Step Failure", "Content not found", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 9: Verify privacy policy and terms of service: ",
                    status ? "PASS" : "FAIL");
            return false;
        }
        driver.close();
        driver.switchTo().window(originalHandle);

        WebElement tos_link= driver.findElement(By.linkText("Terms of Service"));

        tos_link.click();
        new WebDriverWait(driver, 10).until(driver_ -> driver_.getWindowHandles().size() > 1);

        new_url=driver.getCurrentUrl();

        status=old_url.equals(new_url);

        if (!status) {
            logStatus("Step Failure", "URL did not change", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 9: Verify privacy policy and terms of service: ",
                    status ? "PASS" : "FAIL");
            return false;
        }


        for (String windowHandle : driver.getWindowHandles()) {
            if (!originalHandle.equals(windowHandle)) {
                driver.switchTo().window(windowHandle);
                break;
            }
        }

        try{
            driver.findElement(By.xpath("//*[contains(text(),'Terms of Service')]"));
        }
        catch(Exception e){
            status=false;
            logStatus("Step Failure", "Content not found", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 9: Verify privacy policy and terms of service: ",
                    status ? "PASS" : "FAIL");
            return false;
        }
        driver.close();
        driver.switchTo().window(originalHandle);

        WebElement aboutus_link= driver.findElement(By.linkText("About us"));

        aboutus_link.click();
        new WebDriverWait(driver, 10).until(driver_ -> driver_.getWindowHandles().size() > 1);

        new_url=driver.getCurrentUrl();

        status=old_url.equals(new_url);

        if (!status) {
            logStatus("Step Failure", "URL did not change", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 9: Verify privacy policy and terms of service: ",
                    status ? "PASS" : "FAIL");
            return false;
        }


        for (String windowHandle : driver.getWindowHandles()) {
            if (!originalHandle.equals(windowHandle)) {
                driver.switchTo().window(windowHandle);
                break;
            }
        }

        try{
            driver.findElement(By.xpath("//*[contains(text(),'About Us')]"));
        }
        catch(Exception e){
            status=false;
            logStatus("Step Failure", "Content not found", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 9: Verify privacy policy and terms of service: ",
                    status ? "PASS" : "FAIL");
            return false;
        }
        driver.close();
        driver.switchTo().window(originalHandle);

        logStatus("End TestCase",
        "Test Case 9: Verify privacy policy and terms of service: ",
        status ? "PASS" : "FAIL");

        takeScreenshot(driver,"endTestCase","TestCase09");
        return status;
    }

    public static Boolean TestCase10(RemoteWebDriver driver) throws InterruptedException {
        Boolean status = false;
        takeScreenshot(driver,"startTestCase","TestCase10");
        logStatus("Start TestCase", "Test Case 10: Verify contact us link works", "DONE");

        Home homePage = new Home(driver);
        homePage.navigateToHome();

        WebElement contactus= driver.findElement(By.xpath("//p[contains(@class,'footer-text') and contains(text(),'Contact us')]"));
        contactus.click();
        WebElement contactus_box=driver.findElement(By.xpath("//*[contains(@class,'contact-us')]"));
        new WebDriverWait(driver, 10).until(driver_ -> {
            return contactus_box.getText().equals("Contact Us");
        });
        WebElement name_tb=driver.findElement(By.xpath("//input[@placeholder='Name']"));
        name_tb.sendKeys("crio user");

        WebDriverWait wait= new WebDriverWait(driver,10);
        wait.until(driver_ ->{
            return name_tb.getAttribute("value").equals("crio user");
        });
        WebElement email_tb=driver.findElement(By.xpath("//input[@placeholder='Email']"));
        email_tb.sendKeys("criouser@gmail.com");
        wait.until(driver_ ->{
            return email_tb.getAttribute("value").equals("criouser@gmail.com");
        });
        WebElement msg_tb=driver.findElement(By.xpath("//input[@placeholder='Message']"));
        msg_tb.sendKeys("Testing the contact us page");
        wait.until(driver_ ->{
            return msg_tb.getAttribute("value").equals("Testing the contact us page");
        });

        WebElement contactus_b = driver.findElement(By.xpath("//button[contains(text(),'Contact Now')]"));
        contactus_b.click();

        wait.until(driver_->{
            try{
                WebElement contactus_box_=driver_.findElement(By.xpath("//*[contains(@class,'contact-us')]"));
                return !contactus_box_.isDisplayed();
            }
            catch(Exception e){
                return true;
            }   
        });
        
        // TODO: CRIO_TASK_MODULE_SYNCHRONISATION -
        status=true;
        logStatus("End TestCase",
        "Test Case 10: Verify contact us link works: ",
        status ? "PASS" : "FAIL");

        takeScreenshot(driver,"endTestCase","TestCase10");
        return status;
    }

    public static Boolean TestCase11(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestcase", "TestCase11");
        logStatus("Start TestCase",
                "Test Case 11: Verify Advertisemsnts ",
                "DONE");
        Boolean status = false;


        Register registration = new Register(driver);
        registration.navigateToRegisterPage();

        // Register a new user
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("TestCase 11", "Test Case Failure. Happy Flow Test Failed", "FAIL");
        }

        // Save the username of the newly registered user
        lastGeneratedUserName = registration.lastGeneratedUsername;

        // Go to the login page
        Login login = new Login(driver);
        login.navigateToLoginPage();

        // Login with the newly registered user's credentials
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase", "Test Case 11: Happy Flow Test Failed : ", status ? "PASS" : "FAIL");
        }

        // Go to the home page
        Home homePage = new Home(driver);
        homePage.navigateToHome();

        // Find required products by searching and add them to the user's cart
        status = homePage.searchForProduct("YONEX Smash Badminton Racquet");
        homePage.addProductToCart("YONEX Smash Badminton Racquet");

        // Click on the checkout button
        homePage.clickCheckout();

        // Add a new address on the Checkout page and select it
        Checkout checkoutPage = new Checkout(driver);
        checkoutPage.addNewAddress("Addr line 1 addr Line 2 addr line 3");
        checkoutPage.selectAddress("Addr line 1 addr Line 2 addr line 3");

        // Place the order
        checkoutPage.placeOrder();

        WebDriverWait wait = new WebDriverWait(driver, 5);
        wait.until(ExpectedConditions.urlContains("/thanks"));
        status = driver.getCurrentUrl().endsWith("/thanks");

        List<WebElement> Allads = driver.findElements(By.xpath("//iframe"));

        status = Allads.size() == 3;

        for(int i=0;i<=1;i++)
    {
        driver.switchTo().frame(i);

        WebElement chkclk = driver.findElement(By.xpath("//button[text()='Buy Now']"));
        chkclk.click();

        wait.until(ExpectedConditions.urlContains("/checkout"));
        driver.getCurrentUrl().endsWith("/checkout");
        driver.navigate().back();
        driver.switchTo().parentFrame();
    }

    homePage.PerformLogout();

        // TODO: CRIO_TASK_MODULE_SYNCHRONISATION -


        logStatus("End TestCase",
        "Test Case 11: Verify Advertisements ",
        status ? "PASS" : "FAIL");

        return status;

        // Boolean status = false;
        // takeScreenshot(driver,"startTestCase","TestCase11");
        // logStatus("Start TestCase",
        //         "Test Case 11: Verify if ads are displayed correctly",
        //         "DONE");

        // Register registration = new Register(driver);
        // registration.navigateToRegisterPage();
        // status = registration.registerUser("testUser", "abc@123", true);
        // if (!status) {
        //     logStatus("Step Failure", "User Perform Registration Failed", status ? "PASS" : "FAIL");
        //     logStatus("End TestCase",
        //             "Test Case 11: Verify if ads are displayed correctly: ",
        //             status ? "PASS" : "FAIL");
        //     return false;
        // }
        // lastGeneratedUserName = registration.lastGeneratedUsername;

        // Login login = new Login(driver);
        // login.navigateToLoginPage();
        // status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        // if (!status) {
        //     logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
        //     logStatus("End TestCase",
        //             "Test Case 11: Verify if ads are displayed correctly: ",
        //             status ? "PASS" : "FAIL");
        //     return false;
        // }

        // Home homePage = new Home(driver);
        // homePage.navigateToHome();

        // status = homePage.searchForProduct("YONEX Smash Badminton Racquet");
        // homePage.addProductToCart("YONEX Smash Badminton Racquet");

        // homePage.clickCheckout();

        // Checkout checkoutPage = new Checkout(driver);
        // checkoutPage.addNewAddress("Addr line 1 addr Line 2 addr line 3");
        // checkoutPage.selectAddress("Addr line 1 addr Line 2 addr line 3");

        // checkoutPage.placeOrder();
        // // Thread.sleep(3000);
        // WebDriverWait wait = new WebDriverWait(driver, 10);
        // wait.until(d->{
        //     return d.getCurrentUrl().endsWith("/thanks");
        // });

        // List<WebElement> ads=driver.findElements(By.xpath("//iframe"));
        // if(ads.size()!=3){
        //     status=false;
        // }
        // wait.until(ExpectedConditions.frameToBeAvailableAndSwitchToIt(ads.get(0)));
        // // driver.switchTo().frame(ads.get(0));
        // List<WebElement> ad1_buttons=driver.findElements(By.xpath("//button"));
        // for(WebElement but:ad1_buttons){
        //     if (!but.isEnabled()){
        //         status=false;
        //     }
        // }
        // driver.switchTo().defaultContent(); 
        // wait.until(ExpectedConditions.frameToBeAvailableAndSwitchToIt(ads.get(1)));
        // List<WebElement> ad2_buttons=driver.findElements(By.xpath("//button"));
        // for(WebElement but:ad2_buttons){
        //     if (!but.isEnabled()){
        //         status=false;
        //     }
        // }
        // driver.switchTo().defaultContent(); 
        // logStatus("End TestCase",
        // "Test Case 11: Verify if ads are displayed correctly: ",
        // status ? "PASS" : "FAIL");

        // takeScreenshot(driver,"endTestCase","TestCase11");
        // return status;
     
    }

 

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        int totalTests = 0;
        int passedTests = 0;
        Boolean status;
        RemoteWebDriver driver=createDriver();
        // Maximize and Implicit Wait for things to initailize
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

        try {
            // Execute Test Case 1
            totalTests += 1;
            status = TestCase01(driver);
            if (status) {
                passedTests += 1;
            }

            System.out.println("");

            // // Execute Test Case 2
            totalTests += 1;
            status = TestCase02(driver);
            if (status) {
                passedTests += 1;
            }

            System.out.println("");
            // Execute Test Case 3
            totalTests += 1;
            status = TestCase03(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 4
            totalTests += 1;
            status = TestCase04(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 5
            totalTests += 1;
            status = TestCase05(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 6
            totalTests += 1;

            status = TestCase06(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 7
            totalTests += 1;
            status = TestCase07(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 8
            totalTests += 1;
            status = TestCase08(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");
            
            // Execute Test Case 9
            totalTests += 1;
            status = TestCase09(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            //  Execute Test Case 10
             totalTests += 1;
             status = TestCase10(driver);
             if (status) {
             passedTests += 1;
             }
 
             System.out.println("");

            //  Execute Test Case 11
             totalTests += 1;
             status = TestCase11(driver);
             if (status) {
             passedTests += 1;
             }
 
             System.out.println("");

        } catch (Exception e) {
            throw e;
        } finally {
            // quit Chrome Driver
            driver.quit();

            System.out.println(String.format("%s out of %s test cases Passed ", Integer.toString(passedTests),
                    Integer.toString(totalTests)));
        }

    }
}